name: issue_comment trigger
on:  
  issue_comment:  
    types: [created] 
jobs:  
  differentiate_comments:  
    runs-on: ubuntu-latest  
    steps:  
    - name: Check comment type  
      run: |  
          echo "issue_comment"  
