name: pull_request_review trigger
on:  
  pull_request_review:  
    types: [submitted]  
jobs:  
  differentiate_comments:  
    runs-on: ubuntu-latest  
    steps:  
    - name: Check comment type  
      run: |  
          echo "pull_request_review"  
