name: pull_request_review_comment trigger
on:  
  pull_request_review_comment:
    types: [created]
jobs:  
  differentiate_comments:  
    runs-on: ubuntu-latest  
    steps:  
    - name: Check comment type  
      run: |  
          echo "pull_request_review_comment"  
